on: [push]
jobs:
  kernel-4-19:
    runs-on: ubuntu-latest
    container: debian:buster
    steps:
    - uses: actions/checkout@v2
    - name: Update packages
      run: apt-get -y update && apt-get -y upgrade
    - name: Install packages for build
      run: apt-get -y install linux-headers-amd64 build-essential
    - name: Build drivers
      run: make
      env:
        KERNELRELEASE: "4.19.0-9-amd64"
