on: [push]
jobs:
  kernel-4-09:
    runs-on: ubuntu-latest
    container: debian:stretch
    steps:
    - uses: actions/checkout@v2
    - name: Update packages
      run: apt-get -y update && apt-get -y upgrade
    - name: Install packages for build
      run: apt-get -y install linux-headers-amd64 build-essential
    - name: Build drivers
      run: make
      env:
        KERNELRELEASE: "4.9.0-13-amd64"
  kernel-4-19:
    runs-on: ubuntu-latest
    container: debian:buster
    steps:
    - uses: actions/checkout@v2
    - name: Update packages
      run: apt-get -y update && apt-get -y upgrade
    - name: Install packages for build
      run: apt-get -y install linux-headers-amd64 build-essential
    - name: Build drivers
      run: make
      env:
        KERNELRELEASE: "4.19.0-10-amd64"
  kernel-5-07:
    runs-on: ubuntu-latest
    container: debian:bullseye
    steps:
    - uses: actions/checkout@v2
    - name: Update packages
      run: apt-get -y update && apt-get -y upgrade
    - name: Install packages for build
      run: apt-get -y install linux-headers-amd64 build-essential
    - name: Build drivers
      run: make
      env:
        KERNELRELEASE: "5.7.0-2-amd64"
